import { tokensGenerate } from './tokens-generate.js';
import { toTailwindTheme } from '../export/tailwind.js';
import type {
  TailwindGenerateInput,
  TailwindGenerateOutput,
} from './tailwind-generate.schema.js';

/**
 * F9 orchestrator: palette + type_scale + spacing → Tailwind theme-extend config,
 * optionally wrapped in a JS or TS module source string.
 *
 * This tool *composes* F2 (tokens_generate) and F5 (toTailwindTheme); it adds
 * exactly one new piece of logic — semantic-alias resolution — and otherwise
 * just plumbs values through. By design, no new primitives are introduced.
 *
 * Pipeline:
 *   1. F2: tokensGenerate({palette, type_scale, spacing}) → DTCG tree.
 *   2. F5: toTailwindTheme(tree) → Tailwind theme-extend object.
 *   3. If `semantic_map` is given, inject one entry per alias into
 *      `config.colors`, resolving each alias-target to its palette hex value.
 *      Unknown targets throw — silent ignore would mask a config bug.
 *   4. Wrap per `output_format`:
 *        'object'    → return only `{ config }`.
 *        'js-module' → return `{ config, code }` where `code` is a CommonJS
 *                      `module.exports = { theme: { extend: <config> } }` source.
 *        'ts-module' → return `{ config, code }` where `code` is an ESM TS
 *                      `export default { theme: { extend: <config> } } satisfies Config`
 *                      source, including the `import type { Config } from 'tailwindcss'`.
 *
 * Determinism: F2 + F5 are both deterministic; semantic injection iterates the
 * input map's own key order, then alphabetically merges into the existing
 * Tailwind `colors` slot (toTailwindTheme already alpha-sorts that slot, so
 * after our merge we re-sort the final colors keys to keep JSON.stringify
 * byte-stable). The serialized `code` uses `JSON.stringify(..., null, 2)` of
 * the (now-sorted) config object, so identical inputs yield byte-identical
 * source strings.
 *
 * Pure: no I/O, no globals, no Date.now(), no Math.random(). Same input →
 * structurally and stringification-identical output.
 */

/** Sort an object's keys alphabetically, preserving values; non-objects pass through. */
function sortKeysShallow<T extends Record<string, unknown>>(obj: T): T {
  const out: Record<string, unknown> = {};
  for (const key of Object.keys(obj).sort()) {
    out[key] = obj[key];
  }
  return out as T;
}

/**
 * Build the JS-module CommonJS source.
 *
 * Output shape:
 *
 *   /** Generated by @standardbeagle/design-token tailwind_generate. *\/
 *   module.exports = {
 *     theme: {
 *       extend: <config-as-json>,
 *     },
 *   };
 *
 * Uses JSON.stringify so values are quoted JSON-strings (not unquoted JS
 * identifiers); CommonJS treats this as a plain object literal.
 */
function wrapJsModule(config: unknown): string {
  const body = JSON.stringify(config, null, 2);
  return `/** Generated by @standardbeagle/design-token tailwind_generate. */
module.exports = {
  theme: {
    extend: ${body},
  },
};
`;
}

/**
 * Build the TS-module ESM source.
 *
 * Output shape:
 *
 *   /** Generated by @standardbeagle/design-token tailwind_generate. *\/
 *   import type { Config } from 'tailwindcss';
 *
 *   export default {
 *     theme: {
 *       extend: <config-as-json>,
 *     },
 *   } satisfies Pick<Config, 'theme'>;
 *
 * The `Pick<Config, 'theme'>` (rather than bare `Config`) keeps the satisfies
 * narrow — we only emit the `theme` key, so claiming the broader Config shape
 * would be a lie. `Config` requires `content`; `Pick` does not.
 */
function wrapTsModule(config: unknown): string {
  const body = JSON.stringify(config, null, 2);
  return `/** Generated by @standardbeagle/design-token tailwind_generate. */
import type { Config } from 'tailwindcss';

export default {
  theme: {
    extend: ${body},
  },
} satisfies Pick<Config, 'theme'>;
`;
}

export function tailwindGenerate(
  input: TailwindGenerateInput,
): TailwindGenerateOutput {
  const { palette, type_scale, spacing, semantic_map, output_format } = input;

  // Step 1 + 2: compose F2 → F5.
  const dtcg = tokensGenerate({ palette, type_scale, spacing });
  const theme = toTailwindTheme(dtcg);

  // Step 3: semantic-alias injection. Resolve each alias target against the
  // *palette* (the source-of-truth string map) rather than against the already-
  // emitted Tailwind colors object — palette is flat and unambiguous, while
  // Tailwind colors may have been nested by F5 if the palette ever held
  // dotted keys. Resolving against palette also lets us produce a clear error
  // message keyed to the user's input, not a derived structure.
  if (semantic_map) {
    // toTailwindTheme drops the `colors` slot when empty; ensure it exists.
    const colors: Record<string, unknown> = { ...(theme.colors ?? {}) };
    for (const aliasName of Object.keys(semantic_map)) {
      const target = semantic_map[aliasName]!;
      if (!(target in palette)) {
        throw new Error(
          `tailwind_generate: semantic_map alias "${aliasName}" → "${target}" — palette has no entry "${target}". Available: ${Object.keys(palette).sort().join(', ')}`,
        );
      }
      // Resolve to the palette's hex/CSS color string. References are not a
      // Tailwind concept, so we resolve eagerly — Tailwind will see two keys
      // pointing at the same string, which is exactly what design-token
      // aliasing means at the consumer side.
      colors[aliasName] = palette[target]!;
    }
    theme.colors = sortKeysShallow(colors);
  }

  // Step 4: wrap per output_format.
  if (output_format === 'object') {
    return { config: theme };
  }
  if (output_format === 'js-module') {
    return { config: theme, code: wrapJsModule(theme) };
  }
  // ts-module
  return { config: theme, code: wrapTsModule(theme) };
}
